### ISSUE TITLE
RAM leakage

### ISSUE THREAD

**Issue by woox2k** [mate-desktop/eom#139]
Eom does not seem to clean up loaded pictures from RAM when going through thousands of pictures without closing it's window ( using next/prev image) It will continue loading new images to ram until system runs out of it or i close the window.

Steps to reproduce:
1. Find a folder that has more picture files in it than free ram amount
2. Open one picture in eom
3. Use arrow keys to scroll through the entire folder
4. See how eom eats up ram until nothing is left and system hangs.

Sample screen showing eom eat up 6.3GB of RAM:
![ss-20170320-bur2i](https://cloud.githubusercontent.com/assets/5333424/24121102/b2fc6508-0dbf-11e7-9a0a-c17cc46178b9.png)

**Comment by sbalneav** [comment]
Can you check and see if https://github.com/mate-desktop/eom/commit/f62c22e8a3521f47e6517d4414d032c7bd3b4c24 fixes this for you?

**Comment by woox2k** [comment]
Not really sure what this change was supposed to do but the issue remains.
PS. I am getting some weird inconsistent results when comparing my desktop and laptop (both running Arch) On my laptop when browsing through thousands of images (.jpg 1280x800) memory usage grows linearly, just about the amount of memory pictures take on disk. When i try to browse exact same images on my desktop the memory usage is a lot lower with first few thousand pictures and then starts climbing up faster and faster.
For example my laptop took that 6.3GB of ram after browsing through about 6000 images, at 3000 image point it was half that as one might expect. On the other hand on my desktop it takes 1.8GB of ram after those exact same 6000 images and even more weird is that at about 3000-4000 it only takes 500MB of ram that starts to grow faster and faster when i approach 6000 mark. This is consistent between both previous and patched version of eom, nothing has changed as far as i see.

Specs of my PC's:
Desktop:
CPU: Intel Core i7 4770 @ 3.9GHz
RAM: 4x4GB DDR3 @ 2000
Mobo: ASRock Z97 Anniversary
GPU: ASUS GeForce GTX 970 STRIX DirectCU II OC
HDD: Samsung 840 EVO 120GB SSD + 2TB + 2TB + 2TB HDD SATA3

Laptop:
HP Probook 6470b
CPU: Intel i5-3210M 2.5-3.1Ghz
RAM: 8GB DDR3
HDD: Crosair Force 3 SSD 60GB
GPU: Intel HD4000

**Comment by e2gal** [comment]
Happens to me too, I'm using 1.18.2 on Arch x64

**Comment by monsta** [comment]
Could it be the recently fixed GTK+ bug? Check https://github.com/mate-desktop/mate-panel/issues/479 for more info.

**Comment by e2gal** [comment]
Uh, no, I think. I'm on GTK 3.22.18 and still experienced the bug.
The linked issue said that the fix comes in 3.22.4.

**Comment by monsta** [comment]
Ah right, I looked at Ubuntu backports instead. :confused:

**Comment by lukefromdc** [comment]
That commit is indeed missing from eom, and applying it works well. I still found evidence of other memory leaks on opening images from various directories with the image collection showing, but this is one memory leak plugged when applied. About to submit a PR for that, unknown if this memory leak is the same memory leak described in this issue though.

**Comment by lukefromdc** [comment]
https://github.com/mate-desktop/eom/pull/189

Removes a memory leak, but on repeatedly through a directory of maybe a hundred images over and over again the RAM use seemed to grow at about the same rate as in master, not sure why. With each image having a compressed size (jpg) of about 1.5 MB and a 2848x2136 resolution, opening the first image used about 111MB of RAM, and on using the "Next" button to cycle through the directory over and over again RAM use very slowly grew to about 200MB, both with and without the PR.  I wonder if anything else is holding a reference on the image, thus preventing it from being freed?

**Comment by raveit65** [comment]
I tested an directory with about 30 UHD images.
Here eom don't use more than 250MB memory consumption and it goes back to 203 MB if i load next image.
Sorry, I don't have dirs with more images.

**Comment by raveit65** [comment]
With commit from PR and same dir eom starts with 149 MB opening the first image and max value is 240MB.

**Comment by raveit65** [comment]
I merged PR.

**Comment by lukefromdc** [comment]
OK, that's one memory leak plugged. @woox2k , can you test this and see if it resolves or reduced your issue? If not we've got another memory leak that needs to be found next.

**Comment by woox2k** [comment]
![ss-20180821-ctjmq](https://user-images.githubusercontent.com/5333424/44428841-440e3e00-a59e-11e8-92a8-6e8c22c33ee9.png)
Sadly it doesn't resolve my issue. I can confirm that this issue is still there with images saved from motion program, just like the issue in the EOG linked here before. But apparently it also leaks memory when viewing images saved with raspberryPi camera (all other "normal" images i tried worked fine with no leaks)

**Comment by woox2k** [comment]
Files captured with motion seem to have no EXIF data in them but other images i have do (i stopped using motion years ago) They both seem to leak but when i test it on some other random images (like screenshots) it does not leak. I also tried it with normal camera images with loads of EXIF data and even though eom seems to clean up memory at certain intervals with these images it does slowly still creep up.

I also attached sample batch of pictures i have problems with. Note that even by looping through these 27 images eom will just keep using up more ram.
[pic.tar.gz](https://github.com/mate-desktop/eom/files/2309373/pic.tar.gz)

**Comment by raveit65** [comment]
When opening a file from your dir and pressing/hold down the next button for let say 1min, i was able to increase memory consumption up to 113MB. During hold down the button cpu doesn't use more than 44% (AMD 4/8 core)
Sadly eom stays at this value when i do nothing.
Interesting is the eog has the same problem, but eog use 88% cpu when i hold down the next button about one min.

**Comment by woox2k** [comment]
Since this leak occurs even with small selection of images, shouldn't the memory be filled up with repeating data? If so then shouldn't it be quite easy to figure out what data it is with some debug tools? (no experience in this)

**Comment by rcaridade145** [comment]
Would something like [https://scan.coverity.com/](url) be of use?

**Comment by lukefromdc** [comment]
Their website speaks of "registered users" and that sort of thing. Since I do not permit closed, activated, or registered software on any of my systems I cannot use it. A run under Valgrind might produce results but I am an amateur at interpreting Valgrind results. A quick test with Valgrind (under which EOM is incredibly slow) shows a lot of 
Conditional jump or move depends on uninitialised value(s)
errors.

Scrolling through a few images I got this:

luke@ubuntu:~$ valgrind eom
==10732== Memcheck, a memory error detector
==10732== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==10732== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==10732== Command: eom
==10732== 
==10732== Conditional jump or move depends on uninitialised value(s)
==10732==    at 0xBB47C3F: ??? (in /usr/lib/x86_64-linux-gnu/libpixman-1.so.0.34.0)
==10732==    by 0xBB2B97B: ??? (in /usr/lib/x86_64-linux-gnu/libpixman-1.so.0.34.0)
==10732==    by 0xBAE6840: pixman_image_composite32 (in /usr/lib/x86_64-linux-gnu/libpixman-1.so.0.34.0)
==10732==    by 0x78C7C8A: ??? (in /usr/lib/x86_64-linux-gnu/libcairo.so.2.11510.0)
==10732==    by 0x790E3E1: ??? (in /usr/lib/x86_64-linux-gnu/libcairo.so.2.11510.0)
==10732==    by 0x78FFE0E: ??? (in /usr/lib/x86_64-linux-gnu/libcairo.so.2.11510.0)
==10732==    by 0x79008DE: ??? (in /usr/lib/x86_64-linux-gnu/libcairo.so.2.11510.0)
==10732==    by 0x7901491: ??? (in /usr/lib/x86_64-linux-gnu/libcairo.so.2.11510.0)
==10732==    by 0x78BB236: ??? (in /usr/lib/x86_64-linux-gnu/libcairo.so.2.11510.0)
==10732==    by 0x78CCF91: ??? (in /usr/lib/x86_64-linux-gnu/libcairo.so.2.11510.0)
==10732==    by 0x7905348: ??? (in /usr/lib/x86_64-linux-gnu/libcairo.so.2.11510.0)
==10732==    by 0x78C31C3: ??? (in /usr/lib/x86_64-linux-gnu/libcairo.so.2.11510.0)
==10732== 
==10732== Conditional jump or move depends on uninitialised value(s)
==10732==    at 0xBB479DE: ??? (in /usr/lib/x86_64-linux-gnu/libpixman-1.so.0.34.0)
==10732==    by 0xBB2B97B: ??? (in /usr/lib/x86_64-linux-gnu/libpixman-1.so.0.34.0)
==10732==    by 0xBAE6840: pixman_image_composite32 (in /usr/lib/x86_64-linux-gnu/libpixman-1.so.0.34.0)
==10732==    by 0x78C7C8A: ??? (in /usr/lib/x86_64-linux-gnu/libcairo.so.2.11510.0)
==10732==    by 0x790E3E1: ??? (in /usr/lib/x86_64-linux-gnu/libcairo.so.2.11510.0)
==10732==    by 0x78FFE0E: ??? (in /usr/lib/x86_64-linux-gnu/libcairo.so.2.11510.0)
==10732==    by 0x79008DE: ??? (in /usr/lib/x86_64-linux-gnu/libcairo.so.2.11510.0)
==10732==    by 0x7901491: ??? (in /usr/lib/x86_64-linux-gnu/libcairo.so.2.11510.0)
==10732==    by 0x78BB236: ??? (in /usr/lib/x86_64-linux-gnu/libcairo.so.2.11510.0)
==10732==    by 0x78CCF91: ??? (in /usr/lib/x86_64-linux-gnu/libcairo.so.2.11510.0)
==10732==    by 0x7905348: ??? (in /usr/lib/x86_64-linux-gnu/libcairo.so.2.11510.0)
==10732==    by 0x78C31C3: ??? (in /usr/lib/x86_64-linux-gnu/libcairo.so.2.11510.0)
==10732== 
==10732== Conditional jump or move depends on uninitialised value(s)
==10732==    at 0x74B528E: ??? (in /usr/lib/x86_64-linux-gnu/librsvg-2.so.2.40.20)
==10732==    by 0x74B6270: rsvg_handle_get_pixbuf_sub (in /usr/lib/x86_64-linux-gnu/librsvg-2.so.2.40.20)
==10732==    by 0x14436D66: ??? (in /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so)
==10732==    by 0x787E402: gdk_pixbuf_loader_close (in /usr/lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0.3612.0)
==10732==    by 0x787AE4A: ??? (in /usr/lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0.3612.0)
==10732==    by 0x787BD6C: gdk_pixbuf_new_from_stream_at_scale (in /usr/lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0.3612.0)
==10732==    by 0x5B6F889: ??? (in /usr/lib/x86_64-linux-gnu/libgtk-3.so.0.2301.0)
==10732==    by 0x5B729E7: gtk_icon_info_load_icon (in /usr/lib/x86_64-linux-gnu/libgtk-3.so.0.2301.0)
==10732==    by 0x5B72C43: gtk_icon_theme_load_icon_for_scale (in /usr/lib/x86_64-linux-gnu/libgtk-3.so.0.2301.0)
==10732==    by 0x5CEE8EA: ??? (in /usr/lib/x86_64-linux-gnu/libgtk-3.so.0.2301.0)
==10732==    by 0x5CEFD4F: ??? (in /usr/lib/x86_64-linux-gnu/libgtk-3.so.0.2301.0)
==10732==    by 0x5CF6F9A: ??? (in /usr/lib/x86_64-linux-gnu/libgtk-3.so.0.2301.0)
==10732==

**Comment by lukefromdc** [comment]
On closing eom and getting Valgrind's more complete report I got this, with just two or three images having been scrolled through:
```

luke@ubuntu:~$ valgrind eom
==10732== Memcheck, a memory error detector
==10732== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==10732== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==10732== Command: eom
==10732== 
==10732== Conditional jump or move depends on uninitialised value(s)
==10732==    at 0xBB47C3F: ??? (in /usr/lib/x86_64-linux-gnu/libpixman-1.so.0.34.0)
==10732==    by 0xBB2B97B: ??? (in /usr/lib/x86_64-linux-gnu/libpixman-1.so.0.34.0)
==10732==    by 0xBAE6840: pixman_image_composite32 (in /usr/lib/x86_64-linux-gnu/libpixman-1.so.0.34.0)
==10732==    by 0x78C7C8A: ??? (in /usr/lib/x86_64-linux-gnu/libcairo.so.2.11510.0)
==10732==    by 0x790E3E1: ??? (in /usr/lib/x86_64-linux-gnu/libcairo.so.2.11510.0)
==10732==    by 0x78FFE0E: ??? (in /usr/lib/x86_64-linux-gnu/libcairo.so.2.11510.0)
==10732==    by 0x79008DE: ??? (in /usr/lib/x86_64-linux-gnu/libcairo.so.2.11510.0)
==10732==    by 0x7901491: ??? (in /usr/lib/x86_64-linux-gnu/libcairo.so.2.11510.0)
==10732==    by 0x78BB236: ??? (in /usr/lib/x86_64-linux-gnu/libcairo.so.2.11510.0)
==10732==    by 0x78CCF91: ??? (in /usr/lib/x86_64-linux-gnu/libcairo.so.2.11510.0)
==10732==    by 0x7905348: ??? (in /usr/lib/x86_64-linux-gnu/libcairo.so.2.11510.0)
==10732==    by 0x78C31C3: ??? (in /usr/lib/x86_64-linux-gnu/libcairo.so.2.11510.0)
==10732== 
==10732== Conditional jump or move depends on uninitialised value(s)
==10732==    at 0xBB479DE: ??? (in /usr/lib/x86_64-linux-gnu/libpixman-1.so.0.34.0)
==10732==    by 0xBB2B97B: ??? (in /usr/lib/x86_64-linux-gnu/libpixman-1.so.0.34.0)
==10732==    by 0xBAE6840: pixman_image_composite32 (in /usr/lib/x86_64-linux-gnu/libpixman-1.so.0.34.0)
==10732==    by 0x78C7C8A: ??? (in /usr/lib/x86_64-linux-gnu/libcairo.so.2.11510.0)
==10732==    by 0x790E3E1: ??? (in /usr/lib/x86_64-linux-gnu/libcairo.so.2.11510.0)
==10732==    by 0x78FFE0E: ??? (in /usr/lib/x86_64-linux-gnu/libcairo.so.2.11510.0)
==10732==    by 0x79008DE: ??? (in /usr/lib/x86_64-linux-gnu/libcairo.so.2.11510.0)
==10732==    by 0x7901491: ??? (in /usr/lib/x86_64-linux-gnu/libcairo.so.2.11510.0)
==10732==    by 0x78BB236: ??? (in /usr/lib/x86_64-linux-gnu/libcairo.so.2.11510.0)
==10732==    by 0x78CCF91: ??? (in /usr/lib/x86_64-linux-gnu/libcairo.so.2.11510.0)
==10732==    by 0x7905348: ??? (in /usr/lib/x86_64-linux-gnu/libcairo.so.2.11510.0)
==10732==    by 0x78C31C3: ??? (in /usr/lib/x86_64-linux-gnu/libcairo.so.2.11510.0)
==10732== 
==10732== Conditional jump or move depends on uninitialised value(s)
==10732==    at 0x74B528E: ??? (in /usr/lib/x86_64-linux-gnu/librsvg-2.so.2.40.20)
==10732==    by 0x74B6270: rsvg_handle_get_pixbuf_sub (in /usr/lib/x86_64-linux-gnu/librsvg-2.so.2.40.20)
==10732==    by 0x14436D66: ??? (in /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so)
==10732==    by 0x787E402: gdk_pixbuf_loader_close (in /usr/lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0.3612.0)
==10732==    by 0x787AE4A: ??? (in /usr/lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0.3612.0)
==10732==    by 0x787BD6C: gdk_pixbuf_new_from_stream_at_scale (in /usr/lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0.3612.0)
==10732==    by 0x5B6F889: ??? (in /usr/lib/x86_64-linux-gnu/libgtk-3.so.0.2301.0)
==10732==    by 0x5B729E7: gtk_icon_info_load_icon (in /usr/lib/x86_64-linux-gnu/libgtk-3.so.0.2301.0)
==10732==    by 0x5B72C43: gtk_icon_theme_load_icon_for_scale (in /usr/lib/x86_64-linux-gnu/libgtk-3.so.0.2301.0)
==10732==    by 0x5CEE8EA: ??? (in /usr/lib/x86_64-linux-gnu/libgtk-3.so.0.2301.0)
==10732==    by 0x5CEFD4F: ??? (in /usr/lib/x86_64-linux-gnu/libgtk-3.so.0.2301.0)
==10732==    by 0x5CF6F9A: ??? (in /usr/lib/x86_64-linux-gnu/libgtk-3.so.0.2301.0)
==10732== 
==10732== 
==10732== HEAP SUMMARY:
==10732==     in use at exit: 24,067,215 bytes in 50,241 blocks
==10732==   total heap usage: 517,749 allocs, 467,508 frees, 119,906,380 bytes allocated
==10732== 
^C==10732== LEAK SUMMARY:
==10732==    definitely lost: 23,832 bytes in 27 blocks
==10732==    indirectly lost: 28,423 bytes in 908 blocks
==10732==      possibly lost: 10,508 bytes in 153 blocks
==10732==    still reachable: 23,524,972 bytes in 45,945 blocks
==10732==                       of which reachable via heuristic:
==10732==                         length64           : 10,640 bytes in 158 blocks
==10732==                         newarray           : 2,272 bytes in 62 blocks
==10732==         suppressed: 0 bytes in 0 blocks
==10732== Rerun with --leak-check=full to see details of leaked memory
==10732== 
==10732== For counts of detected and suppressed errors, rerun with: -v
==10732== Use --track-origins=yes to see where uninitialised values come from
==10732== ERROR SUMMARY: 318 errors from 3 contexts (suppressed: 21 from 1)

```

**Comment by rcaridade145** [comment]
@lukefromdc  librsvg has had some memory leak fixes it self on version 2.41 and 2.42 https://gitlab.gnome.org/GNOME/librsvg/blob/master/NEWS notice you are using an older version.
Can that account to something?

**Comment by lukefromdc** [comment]
The images I opened are jpg images, not .svg images. Some of my system icons are .svg and that might be using librsvg. What I have is what Debian Unstable is offering at the moment, it would be too much of a maintainance burden to keep up to date local builds of all the unerlying libraries beyond gtk and glib

**Comment by hewhodares** [comment]
I just want to "bump" this, I often have to pkill eom to free a chunk of memory, and before I do I press (left arrow then right arrow) so what I was viewing (modulo next image) shows in recent documents (and hope this catches them)

It's pretty terrible really. 

I'm happy to work with you to see if it's EOM or if we can push the blame off to a library it uses. 

I cannot say for what kind of images it doesn't like, but "anecdotal evidence" (an empirical pattern I've observed, but not formally) after going through some gifs eom is a lot larger then a folder full of jpegs.

I usually have 5 or 6 open for a long time, going left or right.

Let's get this fixed, it's been ages.

**Comment by Saffith** [comment]
I found three significant memory leaks. I submitted a pull request for two of them, but the third one's trickier. I think it's going to take significantly more work to fix. Sometimes, an image's GdkPixbuf isn't unloaded when switching to a new image. I think this happens if you change images after it's finished loading, but before it's actually displayed.

Starting from gdk_pixbuf_loader_close(), here's what normally happens to the ref_count in a cancelled image load:
```
Old value = 2
New value = 1
0x00007ffff55cfee4 in g_object_unref (_object=0x555555de1d20)
    at ../../../../gobject/gobject.c:3248
3248	../../../../gobject/gobject.c: No such file or directory.
(gdb) bt
#0  0x00007ffff55cfee4 in g_object_unref (_object=0x555555de1d20)
    at ../../../../gobject/gobject.c:3248
#1  0x00007fffdaf85a41 in gdk_pixbuf__jpeg_image_stop_load (data=0x7fffe4197890, error=0x7fffea432a60) at io-jpeg.c:854
#2  0x00007ffff662e8a3 in gdk_pixbuf_loader_close (loader=0x555555a1f820 [GdkPixbufLoader], error=0x555555c6dc18) at gdk-pixbuf-loader.c:822
#3  0x0000555555586b7e in eom_image_real_load (error=0x555555c6dc18, job=<optimized out>, data2read=15, img=0x7fffe41034e0 [EomImage]) at eom-image.c:1074
#4  0x0000555555586b7e in eom_image_load (img=0x7fffe41034e0 [EomImage], data2read=data2read@entry=(EOM_IMAGE_DATA_IMAGE | EOM_IMAGE_DATA_DIMENSION | EOM_IMAGE_DATA_EXIF | EOM_IMAGE_DATA_XMP), job=job@entry=0x555555c6dc00 [EomJobLoad], error=error@entry=0x555555c6dc18) at eom-image.c:1245
#5  0x0000555555593bc0 in eom_job_load_run (job=0x555555c6dc00 [EomJobLoad])
    at eom-jobs.c:338
#6  0x0000555555592a30 in handle_job (job=0x555555c6dc00 [EomJobLoad])
    at eom-job-queue.c:77
#7  0x0000555555592a30 in eom_render_thread (data=<optimized out>)
    at eom-job-queue.c:146
#8  0x00007ffff5318195 in g_thread_proxy (data=0x555555816320)
    at ../../../../glib/gthread.c:784
#9  0x00007ffff4ad16db in start_thread (arg=0x7fffea433700)
    at pthread_create.c:463
#10 0x00007ffff47fa88f in clone ()
---Type <return> to continue, or q <return> to quit---
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95



Old value = 1
New value = 0
0x00007ffff55d0002 in g_object_unref (_object=0x555555de1d20)
    at ../../../../gobject/gobject.c:3337
3337	in ../../../../gobject/gobject.c
(gdb) bt
#0  0x00007ffff55d0002 in g_object_unref (_object=0x555555de1d20)
    at ../../../../gobject/gobject.c:3337
#1  0x00007ffff6629232 in gdk_pixbuf_non_anim_finalize (object=0x555555a16b80 [GdkPixbufNonAnim]) at gdk-pixbuf-animation.c:854
#2  0x00007ffff55d0012 in g_object_unref (_object=0x555555a16b80)
    at ../../../../gobject/gobject.c:3340
#3  0x00007ffff662e211 in gdk_pixbuf_loader_finalize (object=0x555555a1f820 [GdkPixbufLoader]) at gdk-pixbuf-loader.c:238
#4  0x00007ffff55d0012 in g_object_unref (_object=0x555555a1f820)
    at ../../../../gobject/gobject.c:3340
#5  0x00005555555864b0 in eom_image_real_load (error=0x7fffe41034f8, job=<optimized out>, data2read=15, img=0x7fffe41034e0 [EomImage]) at eom-image.c:1160
#6  0x00005555555864b0 in eom_image_load (img=0x7fffe41034e0 [EomImage], data2read=data2read@entry=(EOM_IMAGE_DATA_IMAGE | EOM_IMAGE_DATA_DIMENSION | EOM_IMAGE_DATA_EXIF | EOM_IMAGE_DATA_XMP), job=job@entry=0x555555c6dc00 [EomJobLoad], error=error@entry=0x555555c6dc18) at eom-image.c:1245
#7  0x0000555555593bc0 in eom_job_load_run (job=0x555555c6dc00 [EomJobLoad])
    at eom-jobs.c:338
#8  0x0000555555592a30 in handle_job (job=0x555555c6dc00 [EomJobLoad])
    at eom-job-queue.c:77
#9  0x0000555555592a30 in eom_render_thread (data=<optimized out>)
    at eom-job-queue.c:146
#10 0x00007ffff5318195 in g_thread_proxy (data=0x555555816320)
---Type <return> to continue, or q <return> to quit---
    at ../../../../glib/gthread.c:784
#11 0x00007ffff4ad16db in start_thread (arg=0x7fffea433700)
    at pthread_create.c:463
#12 0x00007ffff47fa88f in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```
But sometimes, this happens instead:
```
Old value = 2
New value = 1
0x00007ffff55cfee4 in g_object_unref (_object=0x555555d5a060)
    at ../../../../gobject/gobject.c:3248
3248	../../../../gobject/gobject.c: No such file or directory.
(gdb) bt
#0  0x00007ffff55cfee4 in g_object_unref (_object=0x555555d5a060)
    at ../../../../gobject/gobject.c:3248
#1  0x00007fffdaf85a41 in gdk_pixbuf__jpeg_image_stop_load (data=0x7fffe4197890, error=0x7fffea432a60) at io-jpeg.c:854
#2  0x00007ffff662e8a3 in gdk_pixbuf_loader_close (loader=0x555555a161a0 [GdkPixbufLoader], error=0x555555dce8d8) at gdk-pixbuf-loader.c:822
#3  0x0000555555586b7e in eom_image_real_load (error=0x555555dce8d8, job=<optimized out>, data2read=15, img=0x7fffe40fc6c0 [EomImage]) at eom-image.c:1074
#4  0x0000555555586b7e in eom_image_load (img=0x7fffe40fc6c0 [EomImage], data2read=data2read@entry=(EOM_IMAGE_DATA_IMAGE | EOM_IMAGE_DATA_DIMENSION | EOM_IMAGE_DATA_EXIF | EOM_IMAGE_DATA_XMP), job=job@entry=0x555555dce8c0 [EomJobLoad], error=error@entry=0x555555dce8d8) at eom-image.c:1245
#5  0x0000555555593bc0 in eom_job_load_run (job=0x555555dce8c0 [EomJobLoad])
    at eom-jobs.c:338
#6  0x0000555555592a30 in handle_job (job=0x555555dce8c0 [EomJobLoad])
    at eom-job-queue.c:77
#7  0x0000555555592a30 in eom_render_thread (data=<optimized out>)
    at eom-job-queue.c:146
#8  0x00007ffff5318195 in g_thread_proxy (data=0x555555816320)
    at ../../../../glib/gthread.c:784
#9  0x00007ffff4ad16db in start_thread (arg=0x7fffea433700)
    at pthread_create.c:463
#10 0x00007ffff47fa88f in clone ()
---Type <return> to continue, or q <return> to quit---
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95



Old value = 1
New value = 2
g_object_ref (_object=0x555555d5a060) at ../../../../gobject/gobject.c:3211
3211	in ../../../../gobject/gobject.c
(gdb) bt
#0  0x00007ffff55cfc51 in g_object_ref (_object=0x555555d5a060)
    at ../../../../gobject/gobject.c:3211
#1  0x0000555555586d62 in eom_image_real_load (error=0x555555dce8d8, job=<optimized out>, data2read=15, img=0x7fffe40fc6c0 [EomImage]) at eom-image.c:1126
#2  0x0000555555586d62 in eom_image_load (img=0x7fffe40fc6c0 [EomImage], data2read=data2read@entry=(EOM_IMAGE_DATA_IMAGE | EOM_IMAGE_DATA_DIMENSION | EOM_IMAGE_DATA_EXIF | EOM_IMAGE_DATA_XMP), job=job@entry=0x555555dce8c0 [EomJobLoad], error=error@entry=0x555555dce8d8) at eom-image.c:1245
#3  0x0000555555593bc0 in eom_job_load_run (job=0x555555dce8c0 [EomJobLoad])
    at eom-jobs.c:338
#4  0x0000555555592a30 in handle_job (job=0x555555dce8c0 [EomJobLoad])
    at eom-job-queue.c:77
#5  0x0000555555592a30 in eom_render_thread (data=<optimized out>)
    at eom-job-queue.c:146
#6  0x00007ffff5318195 in g_thread_proxy (data=0x555555816320)
    at ../../../../glib/gthread.c:784
#7  0x00007ffff4ad16db in start_thread (arg=0x7fffea433700)
    at pthread_create.c:463
#8  0x00007ffff47fa88f in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95



Old value = 2
New value = 1
0x00007ffff55cfee4 in g_object_unref (_object=0x555555d5a060)
    at ../../../../gobject/gobject.c:3248
3248	in ../../../../gobject/gobject.c
(gdb) bt
#0  0x00007ffff55cfee4 in g_object_unref (_object=0x555555d5a060)
    at ../../../../gobject/gobject.c:3248
#1  0x00007ffff6629232 in gdk_pixbuf_non_anim_finalize (object=0x555555a0ff60 [GdkPixbufNonAnim]) at gdk-pixbuf-animation.c:854
#2  0x00007ffff55d0012 in g_object_unref (_object=0x555555a0ff60)
    at ../../../../gobject/gobject.c:3340
#3  0x00007ffff662e211 in gdk_pixbuf_loader_finalize (object=0x555555a161a0 [GdkPixbufLoader]) at gdk-pixbuf-loader.c:238
#4  0x00007ffff55d0012 in g_object_unref (_object=0x555555a161a0)
    at ../../../../gobject/gobject.c:3340
#5  0x00005555555864b0 in eom_image_real_load (error=0x7fffe40fc6d8, job=<optimized out>, data2read=15, img=0x7fffe40fc6c0 [EomImage]) at eom-image.c:1160
#6  0x00005555555864b0 in eom_image_load (img=0x7fffe40fc6c0 [EomImage], data2read=data2read@entry=(EOM_IMAGE_DATA_IMAGE | EOM_IMAGE_DATA_DIMENSION | EOM_IMAGE_DATA_EXIF | EOM_IMAGE_DATA_XMP), job=job@entry=0x555555dce8c0 [EomJobLoad], error=error@entry=0x555555dce8d8) at eom-image.c:1245
#7  0x0000555555593bc0 in eom_job_load_run (job=0x555555dce8c0 [EomJobLoad])
    at eom-jobs.c:338
#8  0x0000555555592a30 in handle_job (job=0x555555dce8c0 [EomJobLoad])
    at eom-job-queue.c:77
#9  0x0000555555592a30 in eom_render_thread (data=<optimized out>)
    at eom-job-queue.c:146
#10 0x00007ffff5318195 in g_thread_proxy (data=0x555555816320)
---Type <return> to continue, or q <return> to quit---
    at ../../../../glib/gthread.c:784
#11 0x00007ffff4ad16db in start_thread (arg=0x7fffea433700)
    at pthread_create.c:463
#12 0x00007ffff47fa88f in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```
